const all = [{
    name: 'Admiral',
    origin: 'England',
    information: "Admiral is an excellent mid-season hops variety derived from grandparent Challenger and likely parent, Northdown. Its exact lineage is unclear. Hailing from Wye College, England it was released to the brewing world in 1998 as a potential high-alpha replacement or complimentary addition to Target hops.",
    purpose: "Bittering",
    flavorProfile: 'Aggressive but smooth bittering with an orange-citrus and herbal resonance',
    alphaAcid: '13%-16.2%',
    betaAcid: '4.8%-6.1%',
    link: ''
  },
  {
    name: "Angus",
    origin: "Czech Republic",
    information: "Agnus is the first high-alpha bittering hop to come out of the Czech Republic. It’s name is derived from Czech hop breeder Frantisek Beranek, who’s surname translated into Latin is Agnum – or Lamb in English. Registered in 2000 and released the following year, Agnus is a bittering hop with strong spicy and herbal notes and has been compared by some to Nugget and Magnum.",
    purpose: "Bittering",
    flavorProfile: "Strong spicy and herbal notes",
    alphaAcid: "9%-14%",
    betaAcid: "4%-6.5%",
    link: ""
  }, {
    name: "Apollo",
    origin: "USA",
    information: "To it’s credit, Apollo’s abundance of alpha acids also come with a sharp, clean bittering profile with other highly desirable factors being great storage stability and disease tolerance. It is usually employed alongside aroma hops in order to achieve balance but when used as a late addition or dry hop itself, some grapefruit notes become evident.",
    purpose: "Bittering",
    flavorProfile: "Sharp, clean bittering, grapefruit notes",
    alphaAcid: "15%-20%",
    betaAcid: "5.5%-8%",
    link: ""
  }, {
    name: "Banner",
    origin: "USA",
    information: "Banner is known to have moderately high alpha acids, a pleasant aroma and a good yield but exhibits poor storability, which along with its mildew susceptibility makes it largely unviable.",
    purpose: "Bittering",
    flavorProfile: "Moderate bittering potential, pleasant aroma",
    alphaAcid: "8.4%-13%",
    betaAcid: "5.3%-8%",
    link: ""
  }, {
    name: "Bitter Gold",
    origin: "USA",
    information: "Released for production in 1999, Bitter Gold is quite versatile and can be used as a bittering or flavor addition imparting strong flavors reminiscent of stone fruit, watermelon and pear.",
    purpose: "Bittering",
    flavorProfile: "Use for bittering only, has no notable aroma",
    alphaAcid: "15.4%-18.8%",
    betaAcid: "6.1%-8%",
    link: ""
  }, {
    name: "Bravo",
    origin: "USA",
    information: "ravo’s high alpha content is largely attributable to its parent variety, Zeus. It’s bittering quality is considered smooth and in addition features light floral aromas and subtle flavors of orange and stone fruit making it highly desirable for use in many different ale styles.",
    purpose: "Bittering",
    flavorProfile: "Spicy, earthy, and lightly floral aroma",
    alphaAcid: "14%-17%",
    betaAcid: "3%-5%",
    link: ""
  }, {
    name: "Brewer's Gold",
    origin: "UK",
    information: "Brewer’s Gold hops were selected by Ernest Stanley Salmon at Wye College in England in 1919 and were the result of the open pollination of a wild hop sourced from Morden, Manitoba. Despite its initial popularity, the advent of super-alpha hop varieties in the 1980’s rendered Brewer’s Gold largely redundant from a commercial perspective.",
    purpose: "Bittering",
    flavorProfile: "Notes of spice and blackcurrant",
    alphaAcid: "7.1%-11.3%",
    betaAcid: "3.3%-6.1%",
    link: ""
  }, {
    name: "Brewer's Gold",
    origin: "USA",
    information: "Sister of Brewer's Gold (UK)",
    purpose: "Bittering",
    flavorProfile: "Notes of spice and blackcurrant",
    alphaAcid: "8.1%-13.1%",
    betaAcid: "3.7%-6.8%",
    link: ""
  }, {
    name: "Bullion",
    origin: "UK",
    information: "Bullion features many of the same brewing traits as its sibling with flavors of dark fruit and elements of spice arising from its use as a mid to late addition. Its bitterness is considered by some to be slightly coarse.",
    purpose: "Bittering",
    flavorProfile: "Elements of spice and dark fruits",
    alphaAcid: "6.7%-12.9%",
    betaAcid: "3.7%-9.1%",
    link: ""
  }, {
    name: "Bullion 10A",
    origin: "UK",
    information: "Though technically still Bullion, Bullion 10A is a heat-treated and meristem-tip cultured version of the original English variety. Developed by the USDA and released in 1972, it was retired from production in the US in 1985 along with the original Bullion following the introduction of super-alpha varieties",
    purpose: "Bittering",
    flavorProfile: "Elements of spice and dark fruits",
    alphaAcid: "8%-13.8%",
    betaAcid: "2.8%-6.9%",
    link: ""
  }, {
    name: "",
    origin: "",
    information: "",
    purpose: "",
    flavorProfile: "",
    alphaAcid: "",
    betaAcid: "",
    link: ""
  }, {
    name: "",
    origin: "",
    information: "",
    purpose: "",
    flavorProfile: "",
    alphaAcid: "",
    betaAcid: "",
    link: ""
  }, {
    name: "",
    origin: "",
    information: "",
    purpose: "",
    flavorProfile: "",
    alphaAcid: "",
    betaAcid: "",
    link: ""
  }, {
    name: "",
    origin: "",
    information: "",
    purpose: "",
    flavorProfile: "",
    alphaAcid: "",
    betaAcid: "",
    link: ""
  }, {
    name: "",
    origin: "",
    information: "",
    purpose: "",
    flavorProfile: "",
    alphaAcid: "",
    betaAcid: "",
    link: ""
  }, {
    name: "",
    origin: "",
    information: "",
    purpose: "",
    flavorProfile: "",
    alphaAcid: "",
    betaAcid: "",
    link: ""
  }, {
    name: "",
    origin: "",
    information: "",
    purpose: "",
    flavorProfile: "",
    alphaAcid: "",
    betaAcid: "",
    link: ""
  }, {
    name: "",
    origin: "",
    information: "",
    purpose: "",
    flavorProfile: "",
    alphaAcid: "",
    betaAcid: "",
    link: ""
  }, {
    name: "",
    origin: "",
    information: "",
    purpose: "",
    flavorProfile: "",
    alphaAcid: "",
    betaAcid: "",
    link: ""
  }, {
    name: "",
    origin: "",
    information: "",
    purpose: "",
    flavorProfile: "",
    alphaAcid: "",
    betaAcid: "",
    link: ""
  }, {
    name: "",
    origin: "",
    information: "",
    purpose: "",
    flavorProfile: "",
    alphaAcid: "",
    betaAcid: "",
    link: ""
  }, {
    name: "",
    origin: "",
    information: "",
    purpose: "",
    flavorProfile: "",
    alphaAcid: "",
    betaAcid: "",
    link: ""
  }, {
    name: "",
    origin: "",
    information: "",
    purpose: "",
    flavorProfile: "",
    alphaAcid: "",
    betaAcid: "",
    link: ""
  }, {
    name: "",
    origin: "",
    information: "",
    purpose: "",
    flavorProfile: "",
    alphaAcid: "",
    betaAcid: "",
    link: ""
  }, {
    name: "",
    origin: "",
    information: "",
    purpose: "",
    flavorProfile: "",
    alphaAcid: "",
    betaAcid: "",
    link: ""
  }, {
    name: "",
    origin: "",
    information: "",
    purpose: "",
    flavorProfile: "",
    alphaAcid: "",
    betaAcid: "",
    link: ""
  }, {
    name: "",
    origin: "",
    information: "",
    purpose: "",
    flavorProfile: "",
    alphaAcid: "",
    betaAcid: "",
    link: ""
  }, {
    name: "",
    origin: "",
    information: "",
    purpose: "",
    flavorProfile: "",
    alphaAcid: "",
    betaAcid: "",
    link: ""
  }, {
    name: "",
    origin: "",
    information: "",
    purpose: "",
    flavorProfile: "",
    alphaAcid: "",
    betaAcid: "",
    link: ""
  }, {
    name: "",
    origin: "",
    information: "",
    purpose: "",
    flavorProfile: "",
    alphaAcid: "",
    betaAcid: "",
    link: ""
  }, {
    name: "",
    origin: "",
    information: "",
    purpose: "",
    flavorProfile: "",
    alphaAcid: "",
    betaAcid: "",
    link: ""
  }, {
    name: "",
    origin: "",
    information: "",
    purpose: "",
    flavorProfile: "",
    alphaAcid: "",
    betaAcid: "",
    link: ""
  }, {
    name: "",
    origin: "",
    information: "",
    purpose: "",
    flavorProfile: "",
    alphaAcid: "",
    betaAcid: "",
    link: ""
  }, {
    name: "",
    origin: "",
    information: "",
    purpose: "",
    flavorProfile: "",
    alphaAcid: "",
    betaAcid: "",
    link: ""
  }, {
    name: "",
    origin: "",
    information: "",
    purpose: "",
    flavorProfile: "",
    alphaAcid: "",
    betaAcid: "",
    link: ""
  }, {
    name: "",
    origin: "",
    information: "",
    purpose: "",
    flavorProfile: "",
    alphaAcid: "",
    betaAcid: "",
    link: ""
  }, {
    name: "",
    origin: "",
    information: "",
    purpose: "",
    flavorProfile: "",
    alphaAcid: "",
    betaAcid: "",
    link: ""
  }, {
    name: "",
    origin: "",
    information: "",
    purpose: "",
    flavorProfile: "",
    alphaAcid: "",
    betaAcid: "",
    link: ""
  }, {
    name: "",
    origin: "",
    information: "",
    purpose: "",
    flavorProfile: "",
    alphaAcid: "",
    betaAcid: "",
    link: ""
  }, {
    name: "",
    origin: "",
    information: "",
    purpose: "",
    flavorProfile: "",
    alphaAcid: "",
    betaAcid: "",
    link: ""
  }, {
    name: "",
    origin: "",
    information: "",
    purpose: "",
    flavorProfile: "",
    alphaAcid: "",
    betaAcid: "",
    link: ""
  }, {
    name: "",
    origin: "",
    information: "",
    purpose: "",
    flavorProfile: "",
    alphaAcid: "",
    betaAcid: "",
    link: ""
  }, {
    name: "",
    origin: "",
    information: "",
    purpose: "",
    flavorProfile: "",
    alphaAcid: "",
    betaAcid: "",
    link: ""
  }, {
    name: "",
    origin: "",
    information: "",
    purpose: "",
    flavorProfile: "",
    alphaAcid: "",
    betaAcid: "",
    link: ""
  }, {
    name: "",
    origin: "",
    information: "",
    purpose: "",
    flavorProfile: "",
    alphaAcid: "",
    betaAcid: "",
    link: ""
  }, {
    name: "",
    origin: "",
    information: "",
    purpose: "",
    flavorProfile: "",
    alphaAcid: "",
    betaAcid: "",
    link: ""
  }, {
    name: "",
    origin: "",
    information: "",
    purpose: "",
    flavorProfile: "",
    alphaAcid: "",
    betaAcid: "",
    link: ""
  },
]